### ISSUE TITLE
Criar App Escola para tratar os dados e regras relacionados à escola

### ISSUE THREAD

**Issue by LucianocLopes** [LucianocLopes/DRP01-PJIC1-T7-G18#1]
Pessoal, esse é uma forma de dividir nossa missão em etapas menores, neste caso podemos utilizar essa issue para discutirmos o que é essencial em um app ESCOLA e quais as regras devemos implementar, o que poderá ser compartilhado entre os outros apps e o que é encapsulado e não poderá ter acesso direto, por exemplo. Conto com a colaboração de todos do grupo.

**Comment by LucianocLopes** [comment]
Boa tarde.

Aqui entendi que devemos ter no App Escola ter todas as tratativas que são pertinentes à escola, exemplo: DADOS DA ESCOLA, ESTRUTURA FISICA DA ESCOLA entre outros e suas regras para que seja possível atender os 12 principios do desenvolvimento agil e tambem poder reaproveitar esse app em outros projetos ou até mesmo neste projeto para melhorias.

**Comment by andreivecascarano** [comment]
acredito que a questão dos horário gerais só deixar para o diretor colocar os horários como recreio, saida e entrada, para os demais seria a consulta mesmo. Areas externas como parque e quadra, tv e chromebook trazer a possibilidade do professor colocar sua grade horária depois de definido a grade horária

**Comment by LucianocLopes** [comment]
Bom dia,

cheguei a seguinte conclusão sobre o app ESCOLA, onde terá as informações da escola e das suas estruturas fisicas de funcionamento.

Reafirmando que ainda existe uma dificuldade grande na criação de um app do 0, mesmo porque exige conhecimento mais aprofundado de todos em algumas linguagens que poucos do grrpo conhecem, neste caso optei por utilizar como plano de funco, uma calendário pronto,, construido em javascript, e que foi possível, atraves de um trabalha de backend, unir e trabalhar nisso.

neste caso cheguei a essa conclusão nas entidades na ESCOLA:

Escola e seus atributos serão:
nome, Char, max_length=150;
cnpj, Char, max_length=18;
insc secretaria, Char, max_length=20;
endereço completo, [[valorado]]
telefone, Char, max_length=9,
email,Char,max_length=254;

EstruturaEscolar  seus atributos serão:
nome, Char, max_length=150;
cnpj, Char, max_length=18;
insc secretaria, Char, max_length=20;
endereço completo, [[valorado]]
telefone, Char, max_length=9,
email,Char,max_length=254;

o app permiitirá todos usuarios acessem, mais cadastros e alterações somente  aos usuarios com permissão de staff para acessar, rerá tambem, uma agenda do mês, da Semana, do Dia e uma lista de eventos gravados por dia.
o script de produção deste app, seguirá o seguinte roteiro
1 - criação de uma branch (schedule) para criação e testes do app.
2 - criação do app, configurações inicial
3 - modelo de dados do app
4 - inclusão do fullcalendar e configurações com o app
5 - definição das views e urls para visialização dos dados em testes
6 - denifições das views e urls para o CRUD da agenda.
7 - testes finais e inclusão na branch master.

**Comment by LucianocLopes** [comment]
1 - criação de uma branch (schedule) para criação e testes do app.
Finalizado

2 - criação do app, configurações inicial
Finalizado

3 - modelo de dados do app
Finalizado

4 - inclusão do fullcalendar e configurações com o app
Finalizado

5 - definição das views e urls para visialização dos dados em testes
Finalizado

6 - denifições das views e urls para o CRUD da agenda.
Finalizado

7 - testes finais e inclusão na branch master.
Finalizado
