### ISSUE TITLE
Criar app Agenda para tratar dados e regras de agenda

### ISSUE THREAD

**Issue by LucianocLopes** [LucianocLopes/DRP01-PJIC1-T7-G18#6]
Pessoal, esse é uma forma de dividir nossa missão em etapas menores, neste caso podemos utilizar essa issue para discutirmos o que é essencial em um app AGENDA e quais as regras devemos implementar, o que poderá ser compartilhado entre os outros apps e o que é encapsulado e não poderá ter acesso direto, por exemplo. Conto com a colaboração de todos do grupo.

**Comment by JonasfsBarros** [comment]
Boa Tarde,
Pessoal sobre a agenda poderiamos colocar uma condição para o diretor avaliar, nas sextas feiras(01 vez por semana), ou mensal antes do inicio do mês seguinte.

**Comment by andreivecascarano** [comment]
na agenda, podemos deixar para professores comunicar apenas faltas (podendo ser abonada, médica, o diretor comunica o resto

**Comment by andreivecascarano** [comment]
pensando nisso também, seria interessante criar uma parte para o professor adjunto consutar as faltas para saber quem ele iria cobrir

**Comment by LucianocLopes** [comment]
Boa noite,

cheguei a seguinte conclusão sobre o app AGENDA, que a principio será um auxliar eletrônico para o Diretor da escola, uma vez que será possivel realizar agendamentos de rotinas, reuniões e atendimetnos ao público.

Existe uma dificuldade grande na criação de um app do 0, mesmo porque exige conhecimento mais aprofundado de todos em algumas linguagens que poucos do grrpo conhecem, neste caso optei por utilizar como plano de funco, uma calendário pronto,, construido em javascript, e que foi possível, atraves de um trabalha de backend, unir e trabalhar nisso.

neste caso teremos os seguintas entidades na Agenda:
 - Evento
 e seus atributos serão:
    title, Char, max_length=200;
    start, DateTime;
    end, DateTime;
    all_day, Boolean.
o app exigirá permissão de staff para acessar, rerá  tambem, uma agenda do mês, da Semana, do Dia e uma lista de eventos gravados por dia.
o script de produção deste app, seguirá o seguinte roteiro
1 - criação de uma branch (schedule) para criação e testes do app.
2 - criação do app, configurações inicial
3 - modelo de dados do app
4 - inclusão do fullcalendar e configurações com o app
5 - definição das views e urls para visialização dos dados em testes
6 - denifições das views e urls para o CRUD da agenda.
7 - testes finais e inclusão na branch main.

**Comment by LucianocLopes** [comment]
1 - criação de uma branch (schedule) para criação e testes do app.
finalizado

2 - criação do app, configurações inicial
finalizado

3 - modelo de dados do app
finalizado

4 - inclusão do fullcalendar e configurações com o app
finalizado

5 - definição das views e urls para visialização dos dados em testes
finalizado

**Comment by LucianocLopes** [comment]
6 - definições das views e urls para o CRUD da agenda
Finalizado

7 - testes finais e inclusão no branch main
Finalizado
